kafka-application:
  message:
    length: 20
  producer:
    enabled: true
    blocking-time: 10    
  consumer:
    enabled: true
    with-error: false
    
spring:
  cloud:
    stream: 
      bindings:
        output:
          destination: reactordemo
          binder: kafka
        input:
          consumer:     
            max-attempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0
          group: reactor.demo
          destination: reactordemo
          binder: kafka
      binders:
          kafka:
            type: kafka
            environment:
              spring:
                kafka:                        
                  brokers: ${KAFKA_HOST:127.0.0.1}
      kafka:
        bindings:
          input:
            consumer:
              autoCommitOffset: true
              enableDlq: true
              dlqName: error.reactordemo                    
