version: '3'
services:
  #######################################
  # Kafka
  #######################################
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
      
  #######################################
  # Zookeeper
  #######################################      
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      
  #######################################
  # MongoDB
  #######################################
  mongodb:
    image: mongo
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db
      - /data/configdb      
