spring:
  application:
    name: webflux-server

server:
  port: 8080

logging:
  level:
    root: INFO

error-controler-advice:
  enabled: false

webflux-server:
  base-path: /api
  github:
    url: https://api.github.com
