CREATE TABLE book (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  isbn VARCHAR(13) NOT NULL
);

INSERT INTO book (title, isbn) VALUES ('Design Patterns: Elements of Reusable Object-Oriented Software', '9780201633610');
INSERT INTO book (title, isbn) VALUES ('Enterprise Integration Patterns: Designing, Building, and Deploying Messaging Solutions', '9780321200686');

CREATE TABLE book_price (
  isbn VARCHAR(13) PRIMARY KEY,
  price NUMERIC NOT NULL
);

INSERT INTO book_price (isbn, price) VALUES ('9780201633610', 50.38);
INSERT INTO book_price (isbn, price) VALUES ('9780321200686', 39.40);
